name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Create models directory
        run: mkdir -p models

      - name: Train model
        run: python src/train.py

      - name: Test model
        run: python src/test_model.py

      - name: Deploy model
        run: |
          echo "Model deployment logic here (e.g., upload to cloud storage)"
          echo "Model saved at: $(ls models/)"